name: Build

on:
  # Triggers the workflow on push events
  push:
    branches: [ develop, release/**, feature/**, master, main ]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ARTIFACT_BASE_NAME: cnmResponse
  # Need to change owner back
  UPLOAD_URL: https://api.github.com/repos/cbanh/cumulus-cnm-response-task
  GITHUB_USER: cbanh

jobs:
  # First job name
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8.0.232'
      - uses: gradle/gradle-build-action@v1
        with:
          gradle-version: 4.0.1
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip3 install -r builder/requirements.txt
      - name: Extract Maven project version
        run: echo ::set-output name=current_version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: get-version
      - name: Show extracted Maven project version
        run: |
          echo ${{ steps.get-version.outputs.current_version }}
          base_ver="$(python3 builder/bump-version.py -v 2.0.0 --get-base)"
          echo "$base_ver"
        
      - name: Bump pre-alpha version
        # If triggered by push to a feature branch
        if: ${{ startsWith(github.ref, 'refs/heads/feature/') }}
        run: |
          git_sha="$(git rev-parse --short ${GITHUB_SHA})"          
          echo "git sha=$git_sha"
          new_ver="${{ steps.get-version.outputs.current_version }}+$git_sha"
          echo "software_version=$new_ver" >> $GITHUB_ENV
      - name: Bump alpha version
        # If triggered by push to the develop branch
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |      
          echo "$base_ver"
      - name: Build new version
        run: |
          echo "New Version is: ${{ env.software_version }}"
          python3 builder/builder2.py -d . -a ${{env.ARTIFACT_BASE_NAME}} -v ${{ env.software_version }}
      # - name: Commit pom.xml
      #   if: contains(github.ref, 'master')
      #   run: |
      #     RELEASE_VERSION="$(cat release/version.txt)"
      #     git config user.name "podaac-cloud-IandA"
      #     echo 'git config user.name completed'
      #     git config user.email curtis.banh@gmail.com
      #     echo 'git config email completed'
      #     git commit -m 'Release:'$RELEASE_VERSION pom.xml
      #     echo 'git committed pom.xml with: '$RELEASE_VERSION
      #     echo 'About to push to branch : '$GIT_LOCAL_BRANCH
      #     echo 'GIT_LOCAL_BRANCH:'$GIT_LOCAL_BRANCH
      #     echo 'GIT_BRANCH:'$GIT_BRANCH
      #     git branch
      #     git status
      #     git push
      #     echo 'git pushed pom.xml with version: '$RELEASE_VERSION
      
      - name: Generate Changelog
        run: |
          chlog=$(cat CHANGELOG.md)
          echo "change_log=$(chlog)" >> $GITHUB_ENV
      - name: Upload and Tag Release
        if: contains(github.ref, 'master')
        run: |
          RELEASE_VERSION="$(cat release/version.txt)"
          echo "*** Release Version is : "$RELEASE_VERSION
          ls -la release
          cp release/*.zip .
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | sed 's/[[:space:]]/ /g' |sed "s/'/ /g")
          echo "COMMIT MESSAGE is: "$COMMIT_MESSAGE          
          curl -v -i -X POST -H "Content-Type:application/json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${UPLOAD_URL}/releases -d '{"tag_name":"v'${RELEASE_VERSION}'","target_commitish": "'${CURRENT_BRANCH}'","name": "v'${RELEASE_VERSION}'","body": "release version v'${RELEASE_VERSION}' created by Github Actions ${{ env.change_log }}", "draft": false,"prerelease": false}' > release_create.out
          cat release_create.out
          ASSET_URL=$(cat release_create.out | grep upload_url |sed 's/^\s*"upload_url": "//' |sed 's/assets.*$/assets/')
          echo "ASSET_URL is: " $ASSET_URL
          echo 'curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "Content-Type: $(file -b --mime-type ${{env.ARTIFACT_BASE_NAME}}-'${RELEASE_VERSION}'.zip)" --data-binary @${{env.ARTIFACT_BASE_NAME}}-'${RELEASE_VERSION}'.zip "'${ASSET_URL}'?name=${{env.ARTIFACT_BASE_NAME}}-'${RELEASE_VERSION}'.zip"'
          curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "Content-Type: $(file -b --mime-type ${{env.ARTIFACT_BASE_NAME}}-${RELEASE_VERSION}.zip)" --data-binary "@${{env.ARTIFACT_BASE_NAME}}-${RELEASE_VERSION}.zip" "${ASSET_URL}?name=${{env.ARTIFACT_BASE_NAME}}-${RELEASE_VERSION}.zip"
      - name: Upload and Tag SNAPSHOT  
        if: ${{ !contains(github.ref, 'master') }}
        run: |
          RELEASE_VERSION="$(cat release/version.txt)"
          cp release/*.zip "${{env.ARTIFACT_BASE_NAME}}-${RELEASE_VERSION}.zip"
          curl -v -i -X POST -H "Content-Type:application/json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${UPLOAD_URL}/releases -d '{"tag_name":"v'${RELEASE_VERSION}'","target_commitish": "'${CURRENT_BRANCH}'","name": "v'${RELEASE_VERSION}'","body": "release version v'${RELEASE_VERSION}' created by Github Actions","draft": false,"prerelease": false}' > release_create.out
          cat release_create.out
          ASSET_URL=$(cat release_create.out | grep upload_url |sed 's/^\s*"upload_url": "//' |sed 's/assets.*$/assets/')
          echo "ASSET_URL is: " $ASSET_URL
          echo 'curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "Content-Type: $(file -b --mime-type ${{env.ARTIFACT_BASE_NAME}}-'${RELEASE_VERSION}'.zip)" --data-binary @${{env.ARTIFACT_BASE_NAME}}-'${RELEASE_VERSION}'.zip "'${ASSET_URL}'?name=${{env.ARTIFACT_BASE_NAME}}-'${RELEASE_VERSION}'.zip"'
          curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "Content-Type: $(file -b --mime-type ${{env.ARTIFACT_BASE_NAME}}-${RELEASE_VERSION}.zip)" --data-binary "@${{env.ARTIFACT_BASE_NAME}}-${RELEASE_VERSION}.zip" "${ASSET_URL}?name=${{env.ARTIFACT_BASE_NAME}}-${RELEASE_VERSION}.zip"
      # - name: "Generate release changelog"
      #   uses: heinrichreimer/github-changelog-generator-action@v2.3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }} 
      # - name: Create Release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body: ${{ env.change_log }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}