name: Build

on:
  # Triggers the workflow on push events
  push:
    branches: [ develop, release/**, feature/**, master, main ]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ARTIFACT_BASE_NAME: cnmResponse
  # Need to change owner back
  UPLOAD_URL: https://api.github.com/repos/cbanh/cumulus-cnm-response-task
  GITHUB_USER: cbanh

jobs:
  # First job name
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Extract Maven project version
        run: echo ::set-output name=current_version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: get-version
      - name: Show extracted Maven project version
        run: echo ${{ steps.get-version.outputs.current_version }}
      - name: Bump pre-alpha version
        # If triggered by push to a feature branch
        if: ${{ startsWith(github.ref, 'refs/heads/feature/') }}
        run: |
          git_sha="$(git rev-parse --short ${GITHUB_SHA})"          
          echo "git sha=$git_sha"
          new_ver="${{ steps.get-version.outputs.current_version }}+$git_sha"
          echo "software_version=$new_ver" >> $GITHUB_ENV
      - name: Build new version
        run: |
          echo "New Version is: ${{ env.software_version }}"
          python3 builder/builder2.py -d . -a ${{env.ARTIFACT_BASE_NAME}} -v ${{ env.software_version }}