name: Build

on:
  # Triggers the workflow on push events
  push:
    branches: [ develop, release/**, feature/**, master, main ]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ARTIFACT_BASE_NAME: cnmResponse
  # Need to change owner back
  UPLOAD_URL: https://api.github.com/repos/cbanh/cumulus-cnm-response-task
  GITHUB_USER: cbanh


jobs:
  # First job name
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Bump pre-alpha version
        # If triggered by push to a feature branch
        if: ${{ startsWith(github.ref, 'refs/heads/feature/') }}
        run: |
          git_sha="$(git rev-parse --short ${GITHUB_SHA})"          
          echo "git sha=$git_sha"